### ISSUE TITLE
"key_id" wasn't supplied

### ISSUE THREAD

**Issue by FeldhackerChrisPFG** [ryanvade/aws-credentials-rotation-action#2]
I'm trying to use the action from an internal repository using a PAT rather then the standard GITHUB_TOKEN, which does not have enough permission to update the secret.  I don't think this really relevant, but wanted to mention it.

When running the action the error is received (repeated twice):  

> Error: Invalid request.
> "key_id" wasn't supplied.
> 

A key_id parameter is identified in the document:
https://docs.github.com/en/rest/reference/actions#create-or-update-a-repository-secret 

Code in other projects that update secrets similarly are passing a key_id parameter:
https://github.com/softprops/aws-credential-rotary/blob/main/src/secrets.ts (line 53)

Proposed solution:
In index.ts, I think another parameter is needed after line 81:
key_id: publicKey.key_id

**Comment by ryanvade** [comment]
Thanks for pointing that out, I don't think the key_id was required when I first made this action.  

I do not know how PATs will work with the action, it should be fine assuming you can get octokit to authenticate with it.  

This action needs to be slightly re-worked to support newer GitHub features such as Environments but that is a different issue.  This one has been fixed.
